import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";
import Header from "./Components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: "100vh" }}>
        <div
          className="flex flex-row h-full"
          style={{ backgroundColor: "#ECEBEB" }}
        >
          <Sidebar />
          <div className="overflow-auto dashboard-layout w-full">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
